# Generated by Django 4.0.4 on 2022-07-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='today_feeling',
            field=models.CharField(choices=[('HAPPY', 'happy'), ('SAD', 'sad'), ('ANGRY', 'angry'), ('SOS0', 'SOSO')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.CharField(default='예은', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(blank=b'I00\n'),
        ),
    ]
